:scheduler:
  :schedule:
    update_appointment_status:
      cron: "* * * * *"
      class: UpdateAppointmentStatusJob
      queue: default
      description: "Update appointment status every 10 minutes"
    